import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'slick-carousel/slick/slick.css'; // Import CSS của slick-carousel
import 'slick-carousel/slick/slick-theme.css'; // Import CSS theme của slick-carousel

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HH_STORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
